version: '3.5'

services:
  nginx_proxy:
    container_name: wtp_nginx_proxy
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wtp_net
    volumes:
      - ./data/certbot/www:/var/www/certbot
  certbot:
    build: ./certbot
    volumes:
      - certs_data:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx_proxy
networks: 
  wtp_net:
    name: wtp_net
volumes:
  certs_data:
