version: '3.5'

services:
  nginx_proxy:
    container_name: wtp_nginx_proxy
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - wtp_net
    volumes:
      - /etc/letsencrypt:certs_data/
networks: 
  wtp_net:
    name: wtp_net
volumes:
  certs_data: