version: '3.5'

services:
  nginx_proxy:
    container_name: wtp_nginx_proxy
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - wtp_net
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    build: ./certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - certs:/etc/letsencrypt
    depends_on:
      - nginx_proxy
networks: 
  wtp_net:
    name: wtp_net
volumes:
  certs:
